[2025-04-11T17:55:35.854+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: M3_GA_pipeline.data_cleaning scheduled__2025-04-05T09:20:00+00:00 [queued]>
[2025-04-11T17:55:35.907+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: M3_GA_pipeline.data_cleaning scheduled__2025-04-05T09:20:00+00:00 [queued]>
[2025-04-11T17:55:35.909+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-04-11T17:55:35.911+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-04-11T17:55:35.912+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-04-11T17:55:36.070+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): data_cleaning> on 2025-04-05 09:20:00+00:00
[2025-04-11T17:55:36.091+0000] {standard_task_runner.py:52} INFO - Started process 224 to run task
[2025-04-11T17:55:36.108+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'M3_GA_pipeline', 'data_cleaning', 'scheduled__2025-04-05T09:20:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_galuh_alifani_DAG.py', '--cfg-path', '/tmp/tmpum6p2s62', '--error-file', '/tmp/tmphrulgc7o']
[2025-04-11T17:55:36.115+0000] {standard_task_runner.py:80} INFO - Job 12: Subtask data_cleaning
[2025-04-11T17:55:36.467+0000] {task_command.py:371} INFO - Running <TaskInstance: M3_GA_pipeline.data_cleaning scheduled__2025-04-05T09:20:00+00:00 [running]> on host cc0ee192f301
[2025-04-11T17:55:36.766+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Galuh
AIRFLOW_CTX_DAG_ID=M3_GA_pipeline
AIRFLOW_CTX_TASK_ID=data_cleaning
AIRFLOW_CTX_EXECUTION_DATE=2025-04-05T09:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-04-05T09:20:00+00:00
[2025-04-11T17:55:56.592+0000] {logging_mixin.py:115} INFO - data has been cleaned
[2025-04-11T17:55:56.886+0000] {python.py:173} INFO - Done. Returned value was: None
[2025-04-11T17:55:56.975+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=M3_GA_pipeline, task_id=data_cleaning, execution_date=20250405T092000, start_date=20250411T175535, end_date=20250411T175556
[2025-04-11T17:55:57.137+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-04-11T17:55:57.752+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
